weights: output/blazeface_1000e/model_final
multi_scale_eval: True
filename: BlazeFace

# datasets
metric: WiderFace
num_classes: 1

TrainDataset:
  WIDERFaceDataSet:
    dataset_dir: data/wider_face
    anno_path: wider_face_split/wider_face_train_bbx_gt.txt
    image_dir: WIDER_train/images
    data_fields: ['image', 'gt_bbox', 'gt_class']

EvalDataset:
  WIDERFaceDataSet:
    dataset_dir: data/wider_face
    anno_path: wider_face_split/wider_face_val_bbx_gt.txt
    image_dir: WIDER_val/images
    data_fields: ['image']

TestDataset:
  ImageFolder:
    use_default_label: true

# reader
worker_num: 2
TrainReader:
  inputs_def:
    num_max_boxes: 90
  sample_transforms:
    - Decode: {}
    - RandomDistort: {brightness: [0.5, 1.125, 0.875], random_apply: False}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomFlip: {}
    - CropWithDataAchorSampling: {
      anchor_sampler: [[1, 10, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.2, 0.0]],
      batch_sampler: [
        [1, 50, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0],
        [1, 50, 0.3, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0],
        [1, 50, 0.3, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0],
        [1, 50, 0.3, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0],
        [1, 50, 0.3, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0],
      ],
      target_size: 640}
    - Resize: {target_size: [640, 640], keep_ratio: False, interp: 1}
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 90}
  batch_transforms:
    - NormalizeImage: {mean:  [123, 117, 104], std: [127.502231, 127.502231, 127.502231], is_scale: false}
    - Permute: {}
  batch_size: 8
  shuffle: true
  drop_last: true


EvalReader:
  sample_transforms:
    - Decode: {}
    - NormalizeImage: {mean:  [123, 117, 104], std: [127.502231, 127.502231, 127.502231], is_scale: false}
    - Permute: {}
  batch_size: 1


TestReader:
  sample_transforms:
    - Decode: {}
    - NormalizeImage: {mean:  [123, 117, 104], std: [127.502231, 127.502231, 127.502231], is_scale: false}
    - Permute: {}
  batch_size: 1


# runtime
use_gpu: true
use_xpu: false
log_iter: 20
save_dir: output
snapshot_epoch: 1
print_flops: false

# optimizer
epoch: 1000

LearningRate:
  base_lr: 0.001
  schedulers:
  - PiecewiseDecay:
      gamma: 0.1
      milestones:
        - 333
        - 800
  - LinearWarmup:
      start_factor: 0.3333333333333333
      steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.0
    type: RMSProp
  regularizer:
    factor: 0.0005
    type: L2

# architecture
architecture: BlazeFace

BlazeFace:
  backbone:
    BlazeNet:
      blaze_filters: [ [ 24, 24 ], [ 24, 24 ], [ 24, 48, 2 ], [ 48, 48 ], [ 48, 48 ] ]
      double_blaze_filters: [ [ 48, 24, 96, 2 ], [ 96, 24, 96 ], [ 96, 24, 96 ],
                              [ 96, 24, 96, 2 ], [ 96, 24, 96 ], [ 96, 24, 96 ] ]
      act: relu
  neck:
    BlazeNeck:
      neck_type: None
      in_channel: [ 96,96 ]
  blaze_head:
    FaceHead:
      in_channels: [ 96,96 ]
      anchor_generator:
          name: AnchorGeneratorSSD
          steps: [ 8., 16. ]
          aspect_ratios: [ [ 1. ], [ 1. ] ]
          min_sizes: [ [ 16.,24. ], [ 32., 48., 64., 80., 96., 128. ] ]
          max_sizes: [ [ ], [ ] ]
          offset: 0.5
          flip: False
          min_max_aspect_ratios_order: false
      loss:
        name: SSDLoss
        overlap_threshold: 0.35
  post_process:
    BBoxPostProcess:
      decode:
        name: SSDBox
      nms:
        name: MultiClassNMS
        keep_top_k: 750
        score_threshold: 0.01
        nms_threshold: 0.3
        nms_top_k: 5000
        nms_eta: 1.0
