pretrain_weights:  https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vd_ssld_v2_pretrained.pdparams
weights: output/solov2_r50_fpn_3x_coco/model_final
epoch: 2 # 36
use_ema: true
ema_decay: 0.9998
filename: 'Solov2'

# datasets

metric: COCO
num_classes: 80

TrainDataset:
  COCODataSet:
    image_dir: val2017
    anno_path: annotations/instances_val2017.json
    dataset_dir: ../
    data_fields: ['image', 'gt_bbox', 'gt_class', 'gt_poly', 'is_crowd']

EvalDataset:
  COCODataSet:
    image_dir: val2017
    anno_path: annotations/instances_val2017.json
    dataset_dir: ../

TestDataset:
  ImageFolder:
    anno_path: annotations/instances_val2017.json # also support txt (like VOC's label_list.txt)
    dataset_dir: dataset/coco # if set, anno_path will be 'dataset_dir/anno_path'

# reader

worker_num: 2
TrainReader:
  sample_transforms:
  - Decode: {}
  - Poly2Mask: {}
  - RandomDistort: {}
  - RandomCrop: {}
  - RandomResize: {interp: 1,
                     target_size: [[352, 852], [384, 852], [416, 852], [448, 852], [480, 852], [512, 852]],
                     keep_ratio: True}
  - RandomFlip: {}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  - Gt2Solov2Target: {num_grids: [40, 36, 24, 16, 12],
                        scale_ranges: [[1, 96], [48, 192], [96, 384], [192, 768], [384, 2048]],
                        coord_sigma: 0.2}
  batch_size: 8
  shuffle: true
  drop_last: true


EvalReader:
  sample_transforms:
  - Decode: {}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Resize: {interp: 1, target_size: [512, 852], keep_ratio: True}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 1
  shuffle: false
  drop_last: True


TestReader:
  sample_transforms:
  - Decode: {}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Resize: {interp: 1, target_size: [512, 852], keep_ratio: True}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 1
  shuffle: false
  drop_last: True


# runtime

use_gpu: true
use_xpu: false
log_iter: 20
save_dir: output
snapshot_epoch: 1
print_flops: false


# architecture
architecture: SOLOv2

SOLOv2:
  backbone:
    ResNet:
      depth: 50
      variant: d
      freeze_at: 0
      freeze_norm: false
      norm_type: sync_bn
      return_idx: [ 0,1,2,3 ]
      dcn_v2_stages: [ 1,2,3 ]
      lr_mult_list: [ 0.05, 0.05, 0.1, 0.15 ]
      num_stages: 4
  neck:
    FPN:
      out_channel: 256
  solov2_head:
    SOLOv2Head:
      seg_feat_channels: 256
      stacked_convs: 3
      num_grids: [ 40, 36, 24, 16, 12 ]
      kernel_out_channels: 128
      solov2_loss:
        name: SOLOv2Loss
        ins_loss_weight: 3.0
        focal_loss_gamma: 2.0
        focal_loss_alpha: 0.25
      mask_nms:
        name: MaskMatrixNMS
        pre_nms_top_n: 500
        post_nms_top_n: 100
      dcn_v2_stages: [ 2 ]
      drop_block: True
  mask_head:
    SOLOv2MaskHead:
      mid_channels: 128
      out_channels: 128
      start_level: 0
      end_level: 3
      use_dcn_in_tower: True

# optimizer

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

LearningRate:
  base_lr: 0.01
  schedulers:
  - PiecewiseDecay:
      gamma: 0.1
      milestones: [24, 33]
  - LinearWarmup:
      start_factor: 0.
      steps: 1000


